name: 'Android'
description: 'Run Android UI Test'
inputs:
  api_version:  # id of input
    description: 'API version'
    required: true
    default: '29'
runs:
  using: "composite"
  steps: 
    - name: Install Android Emulator
      run: echo 'ANDROID_HOME= ${ANDROID_HOME}'
      #yes | sudo ${ANDROID_HOME}/tools/bin/sdkmanager 'system-images;android-${{ inputs.api_version }};google_apis;x86_64' 'emulator' --verbose --sdk_root=${ANDROID_SDK_ROOT}
      shell: bash