name: 'Android'
description: 'Run Android UI Test'
inputs:
  api-version:  # id of input
    description: 'Android API version'
    required: true
    default: '29'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/emulator.sh
      shell: bash